/**
 * Product API
 * API for managing products
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import CreateProductRequest from './model/CreateProductRequest';
import ErrorResponse from './model/ErrorResponse';
import ProductResponse from './model/ProductResponse';
import UpdateProductRequest from './model/UpdateProductRequest';
import DefaultApi from './api/DefaultApi';


/**
* API for managing products.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var ProductClient = require('index'); // See note below*.
* var xxxSvc = new ProductClient.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new ProductClient.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new ProductClient.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new ProductClient.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The CreateProductRequest model constructor.
     * @property {module:model/CreateProductRequest}
     */
    CreateProductRequest,

    /**
     * The ErrorResponse model constructor.
     * @property {module:model/ErrorResponse}
     */
    ErrorResponse,

    /**
     * The ProductResponse model constructor.
     * @property {module:model/ProductResponse}
     */
    ProductResponse,

    /**
     * The UpdateProductRequest model constructor.
     * @property {module:model/UpdateProductRequest}
     */
    UpdateProductRequest,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi
};
