// Code generated by generate-events.sh. DO NOT EDIT.
package events

import "reflect"

// Event type constants - match Avro schema names
const (
	EventTypeProductCreated = "ProductCreatedEvent"
	EventTypeProductUpdated = "ProductUpdatedEvent"
)

// Event is a sealed interface that all event types must implement.
// This enables exhaustiveness checking when using type switches.
type Event interface {
	isEvent() // unexported method seals the interface
}

func (*ProductCreatedEvent) isEvent() {}

func (*ProductUpdatedEvent) isEvent() {}

// Topic constants - Kafka topics from AsyncAPI spec
const (
	TopicCatalogProductEvents = "catalog.product.events"
)

// Schema name constants - Avro schema full names (namespace.name)
const (
	SchemaNameProductCreated = "com.ecommerce.events.product.ProductCreatedEvent"
	SchemaNameProductUpdated = "com.ecommerce.events.product.ProductUpdatedEvent"
)

// TypeRegistration contains schema registration data for TypeMapping.
type TypeRegistration struct {
	GoType     reflect.Type
	SchemaJSON []byte
	SchemaName string
	Topic      string
}

// TypeRegistrations contains all event type registrations.
// Use this to register all schemas in your microservice.
var TypeRegistrations = []TypeRegistration{
	{
		GoType:     reflect.TypeOf(ProductCreatedEvent{}),
		SchemaJSON: ProductCreatedCombinedSchema,
		SchemaName: SchemaNameProductCreated,
		Topic:      TopicCatalogProductEvents,
	},
	{
		GoType:     reflect.TypeOf(ProductUpdatedEvent{}),
		SchemaJSON: ProductUpdatedCombinedSchema,
		SchemaName: SchemaNameProductUpdated,
		Topic:      TopicCatalogProductEvents,
	},
}
