// Code generated by avro/gen. DO NOT EDIT.
package events

import (
	"time"
)

// Common event metadata used by all domain events. Contains technical/observability fields separate from business payload.
type EventMetadata struct {
	// Unique event identifier (UUID).
	EventID string `avro:"event_id" json:"event_id"`
	// Type of the event (e.g., ProductCreated, ProductUpdated).
	EventType string `avro:"event_type" json:"event_type"`
	// Source service that produced the event.
	Source string `avro:"source" json:"source"`
	// Event creation timestamp in milliseconds since epoch.
	Timestamp time.Time `avro:"timestamp" json:"timestamp"`
	// OpenTelemetry trace ID for distributed tracing.
	TraceID *string `avro:"trace_id" json:"trace_id"`
	// Correlation ID for request tracking across services.
	CorrelationID *string `avro:"correlation_id" json:"correlation_id"`
}

// Business data for product creation event.
type ProductCreatedPayload struct {
	// Unique product identifier (UUID).
	ProductID string `avro:"product_id" json:"product_id"`
	// Product name.
	Name string `avro:"name" json:"name"`
	// Product price.
	Price float32 `avro:"price" json:"price"`
	// Available quantity.
	Quantity int `avro:"quantity" json:"quantity"`
	// Optional image identifier.
	ImageID *string `avro:"image_id" json:"image_id"`
	// Whether the product is enabled.
	Enabled bool `avro:"enabled" json:"enabled"`
	// Entity version for optimistic locking.
	Version int `avro:"version" json:"version"`
	// Product creation timestamp.
	CreatedAt time.Time `avro:"created_at" json:"created_at"`
	// Product last modification timestamp.
	ModifiedAt time.Time `avro:"modified_at" json:"modified_at"`
}

// Event emitted when a new product is created.
type ProductCreatedEvent struct {
	// Event metadata containing technical and observability fields.
	Metadata EventMetadata `avro:"metadata" json:"metadata"`
	// Product business data at the time of creation.
	Payload ProductCreatedPayload `avro:"payload" json:"payload"`
}

// Business data for product update event.
type ProductUpdatedPayload struct {
	// Unique product identifier (UUID).
	ProductID string `avro:"product_id" json:"product_id"`
	// Product name.
	Name string `avro:"name" json:"name"`
	// Product price.
	Price float32 `avro:"price" json:"price"`
	// Available quantity.
	Quantity int `avro:"quantity" json:"quantity"`
	// Optional image identifier.
	ImageID *string `avro:"image_id" json:"image_id"`
	// Whether the product is enabled.
	Enabled bool `avro:"enabled" json:"enabled"`
	// Entity version for optimistic locking.
	Version int `avro:"version" json:"version"`
	// Product creation timestamp.
	CreatedAt time.Time `avro:"created_at" json:"created_at"`
	// Product last modification timestamp.
	ModifiedAt time.Time `avro:"modified_at" json:"modified_at"`
}

// Event emitted when a product is updated.
type ProductUpdatedEvent struct {
	// Event metadata containing technical and observability fields.
	Metadata EventMetadata `avro:"metadata" json:"metadata"`
	// Product business data after the update.
	Payload ProductUpdatedPayload `avro:"payload" json:"payload"`
}
