// Code generated by generate-events.sh. DO NOT EDIT.
package events

import _ "embed"

//go:embed asyncapi.yaml
var AsyncAPISpec []byte

//go:embed schemas/event_metadata.avsc
var EventMetadataSchema []byte

//go:embed schemas/product_created.avsc
var ProductCreatedSchema []byte

//go:embed schemas/product_updated.avsc
var ProductUpdatedSchema []byte

// Combined schemas with EventMetadata inlined for Avro serialization

//go:embed schemas/product_created_combined.json
var ProductCreatedCombinedSchema []byte

//go:embed schemas/product_updated_combined.json
var ProductUpdatedCombinedSchema []byte

