/**
 * Product API
 * API for managing products
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProductResponse model module.
 * @module model/ProductResponse
 * @version 1.0.0
 */
class ProductResponse {
    /**
     * Constructs a new <code>ProductResponse</code>.
     * @alias module:model/ProductResponse
     * @param id {String} 
     * @param version {Number} 
     * @param name {String} 
     * @param price {Number} 
     * @param quantity {Number} 
     * @param enabled {Boolean} 
     * @param createdAt {Date} 
     * @param modifiedAt {Date} 
     */
    constructor(id, version, name, price, quantity, enabled, createdAt, modifiedAt) { 
        
        ProductResponse.initialize(this, id, version, name, price, quantity, enabled, createdAt, modifiedAt);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, version, name, price, quantity, enabled, createdAt, modifiedAt) { 
        obj['id'] = id;
        obj['version'] = version;
        obj['name'] = name;
        obj['price'] = price;
        obj['quantity'] = quantity;
        obj['enabled'] = enabled;
        obj['createdAt'] = createdAt;
        obj['modifiedAt'] = modifiedAt;
    }

    /**
     * Constructs a <code>ProductResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProductResponse} obj Optional instance to populate.
     * @return {module:model/ProductResponse} The populated <code>ProductResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductResponse();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
            if (data.hasOwnProperty('quantity')) {
                obj['quantity'] = ApiClient.convertToType(data['quantity'], 'Number');
            }
            if (data.hasOwnProperty('enabled')) {
                obj['enabled'] = ApiClient.convertToType(data['enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
            }
            if (data.hasOwnProperty('modifiedAt')) {
                obj['modifiedAt'] = ApiClient.convertToType(data['modifiedAt'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProductResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProductResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ProductResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }

        return true;
    }


}

ProductResponse.RequiredProperties = ["id", "version", "name", "price", "quantity", "enabled", "createdAt", "modifiedAt"];

/**
 * @member {String} id
 */
ProductResponse.prototype['id'] = undefined;

/**
 * @member {Number} version
 */
ProductResponse.prototype['version'] = undefined;

/**
 * @member {String} name
 */
ProductResponse.prototype['name'] = undefined;

/**
 * @member {Number} price
 */
ProductResponse.prototype['price'] = undefined;

/**
 * @member {Number} quantity
 */
ProductResponse.prototype['quantity'] = undefined;

/**
 * @member {Boolean} enabled
 */
ProductResponse.prototype['enabled'] = undefined;

/**
 * @member {Date} createdAt
 */
ProductResponse.prototype['createdAt'] = undefined;

/**
 * @member {Date} modifiedAt
 */
ProductResponse.prototype['modifiedAt'] = undefined;






export default ProductResponse;

