// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for GetListParamsSort.
const (
	CreatedAt  GetListParamsSort = "createdAt"
	ModifiedAt GetListParamsSort = "modifiedAt"
	Name       GetListParamsSort = "name"
	Price      GetListParamsSort = "price"
	Quantity   GetListParamsSort = "quantity"
)

// Defines values for GetListParamsOrder.
const (
	Asc  GetListParamsOrder = "asc"
	Desc GetListParamsOrder = "desc"
)

// Problem RFC7807 Problem Details
type Problem struct {
	Detail *string `json:"detail,omitempty"`
	Errors *[]struct {
		Field   *string `json:"field,omitempty"`
		Message *string `json:"message,omitempty"`
	} `json:"errors,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   int     `json:"status"`
	Title    string  `json:"title"`
	TraceId  *string `json:"traceId,omitempty"`
	Type     string  `json:"type"`
}

// ProductListResponse defines model for ProductListResponse.
type ProductListResponse struct {
	Items []ProductResponse `json:"items"`

	// Page Current page number
	Page int `json:"page"`

	// Size Number of items per page
	Size int `json:"size"`

	// Total Total number of items
	Total int `json:"total"`
}

// ProductResponse defines model for ProductResponse.
type ProductResponse struct {
	CreatedAt  time.Time `json:"createdAt"`
	Enabled    bool      `json:"enabled"`
	Id         string    `json:"id"`
	ImageId    *string   `json:"imageId,omitempty"`
	ModifiedAt time.Time `json:"modifiedAt"`
	Name       string    `json:"name"`
	Price      float32   `json:"price"`
	Quantity   int       `json:"quantity"`
	Version    int       `json:"version"`
}

// CreateProductJSONBody defines parameters for CreateProduct.
type CreateProductJSONBody struct {
	Enabled  bool                `json:"enabled"`
	Id       *openapi_types.UUID `json:"id,omitempty"`
	ImageId  *string             `json:"imageId,omitempty"`
	Name     string              `json:"name"`
	Price    float32             `json:"price"`
	Quantity int                 `json:"quantity"`
}

// GetListParams defines parameters for GetList.
type GetListParams struct {
	// Page Page number (must be greater than 0)
	Page int `form:"page" json:"page"`

	// Size Number of items per page (max 100)
	Size int `form:"size" json:"size"`

	// Enabled Filter by enabled status
	Enabled *bool `form:"enabled,omitempty" json:"enabled,omitempty"`

	// Sort Field to sort by
	Sort *GetListParamsSort `form:"sort,omitempty" json:"sort,omitempty"`

	// Order Sort order (ascending or descending)
	Order *GetListParamsOrder `form:"order,omitempty" json:"order,omitempty"`
}

// GetListParamsSort defines parameters for GetList.
type GetListParamsSort string

// GetListParamsOrder defines parameters for GetList.
type GetListParamsOrder string

// UpdateProductJSONBody defines parameters for UpdateProduct.
type UpdateProductJSONBody struct {
	Enabled  bool               `json:"enabled"`
	Id       openapi_types.UUID `json:"id"`
	ImageId  *string            `json:"imageId,omitempty"`
	Name     string             `json:"name"`
	Price    float32            `json:"price"`
	Quantity int                `json:"quantity"`
	Version  int                `json:"version"`
}

// CreateProductJSONRequestBody defines body for CreateProduct for application/json ContentType.
type CreateProductJSONRequestBody CreateProductJSONBody

// UpdateProductJSONRequestBody defines body for UpdateProduct for application/json ContentType.
type UpdateProductJSONRequestBody UpdateProductJSONBody
