// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Problem RFC7807 Problem Details
type Problem struct {
	Detail *string `json:"detail,omitempty"`
	Errors *[]struct {
		Field   *string `json:"field,omitempty"`
		Message *string `json:"message,omitempty"`
	} `json:"errors,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   int     `json:"status"`
	Title    string  `json:"title"`
	TraceId  *string `json:"traceId,omitempty"`
	Type     *string `json:"type,omitempty"`
}

// ProductResponse defines model for ProductResponse.
type ProductResponse struct {
	CreatedAt  time.Time `json:"createdAt"`
	Enabled    bool      `json:"enabled"`
	Id         string    `json:"id"`
	ModifiedAt time.Time `json:"modifiedAt"`
	Name       string    `json:"name"`
	Price      float32   `json:"price"`
	Quantity   int       `json:"quantity"`
	Version    int       `json:"version"`
}

// CreateProductJSONBody defines parameters for CreateProduct.
type CreateProductJSONBody struct {
	Enabled  bool                `json:"enabled"`
	Id       *openapi_types.UUID `json:"id,omitempty"`
	ImageId  *string             `json:"imageId,omitempty"`
	Name     string              `json:"name"`
	Price    float32             `json:"price"`
	Quantity int                 `json:"quantity"`
}

// UpdateProductJSONBody defines parameters for UpdateProduct.
type UpdateProductJSONBody struct {
	Enabled  bool               `json:"enabled"`
	Id       openapi_types.UUID `json:"id"`
	ImageId  *string            `json:"imageId,omitempty"`
	Name     string             `json:"name"`
	Price    float32            `json:"price"`
	Quantity int                `json:"quantity"`
	Version  int                `json:"version"`
}

// CreateProductJSONRequestBody defines body for CreateProduct for application/json ContentType.
type CreateProductJSONRequestBody CreateProductJSONBody

// UpdateProductJSONRequestBody defines body for UpdateProduct for application/json ContentType.
type UpdateProductJSONRequestBody UpdateProductJSONBody
