// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create a new product
	// (POST /v1/product/create)
	CreateProduct(c *gin.Context)
	// Get a product by ID
	// (GET /v1/product/get/{id})
	GetProductById(c *gin.Context, id string)
	// Get a paginated list of products with filtering and sorting
	// (GET /v1/product/list)
	GetList(c *gin.Context, params GetListParams)
	// Update an existing product
	// (PUT /v1/product/update)
	UpdateProduct(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// CreateProduct operation middleware
func (siw *ServerInterfaceWrapper) CreateProduct(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateProduct(c)
}

// GetProductById operation middleware
func (siw *ServerInterfaceWrapper) GetProductById(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetProductById(c, id)
}

// GetList operation middleware
func (siw *ServerInterfaceWrapper) GetList(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetListParams

	// ------------- Required query parameter "page" -------------

	if paramValue := c.Query("page"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument page is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "size" -------------

	if paramValue := c.Query("size"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument size is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "size", c.Request.URL.Query(), &params.Size)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter size: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "enabled" -------------

	err = runtime.BindQueryParameter("form", true, false, "enabled", c.Request.URL.Query(), &params.Enabled)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter enabled: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", c.Request.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameter("form", true, false, "order", c.Request.URL.Query(), &params.Order)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter order: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetList(c, params)
}

// UpdateProduct operation middleware
func (siw *ServerInterfaceWrapper) UpdateProduct(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateProduct(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/v1/product/create", wrapper.CreateProduct)
	router.GET(options.BaseURL+"/v1/product/get/:id", wrapper.GetProductById)
	router.GET(options.BaseURL+"/v1/product/list", wrapper.GetList)
	router.PUT(options.BaseURL+"/v1/product/update", wrapper.UpdateProduct)
}

type CreateProductRequestObject struct {
	Body *CreateProductJSONRequestBody
}

type CreateProductResponseObject interface {
	VisitCreateProductResponse(w http.ResponseWriter) error
}

type CreateProduct200JSONResponse ProductResponse

func (response CreateProduct200JSONResponse) VisitCreateProductResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreateProduct400ApplicationProblemPlusJSONResponse Problem

func (response CreateProduct400ApplicationProblemPlusJSONResponse) VisitCreateProductResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateProduct500ApplicationProblemPlusJSONResponse Problem

func (response CreateProduct500ApplicationProblemPlusJSONResponse) VisitCreateProductResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetProductByIdRequestObject struct {
	Id string `json:"id"`
}

type GetProductByIdResponseObject interface {
	VisitGetProductByIdResponse(w http.ResponseWriter) error
}

type GetProductById200JSONResponse ProductResponse

func (response GetProductById200JSONResponse) VisitGetProductByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetProductById404ApplicationProblemPlusJSONResponse Problem

func (response GetProductById404ApplicationProblemPlusJSONResponse) VisitGetProductByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetProductById500ApplicationProblemPlusJSONResponse Problem

func (response GetProductById500ApplicationProblemPlusJSONResponse) VisitGetProductByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetListRequestObject struct {
	Params GetListParams
}

type GetListResponseObject interface {
	VisitGetListResponse(w http.ResponseWriter) error
}

type GetList200JSONResponse ProductListResponse

func (response GetList200JSONResponse) VisitGetListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetList400ApplicationProblemPlusJSONResponse Problem

func (response GetList400ApplicationProblemPlusJSONResponse) VisitGetListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetList500ApplicationProblemPlusJSONResponse Problem

func (response GetList500ApplicationProblemPlusJSONResponse) VisitGetListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateProductRequestObject struct {
	Body *UpdateProductJSONRequestBody
}

type UpdateProductResponseObject interface {
	VisitUpdateProductResponse(w http.ResponseWriter) error
}

type UpdateProduct200JSONResponse ProductResponse

func (response UpdateProduct200JSONResponse) VisitUpdateProductResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateProduct400ApplicationProblemPlusJSONResponse Problem

func (response UpdateProduct400ApplicationProblemPlusJSONResponse) VisitUpdateProductResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateProduct412ApplicationProblemPlusJSONResponse Problem

func (response UpdateProduct412ApplicationProblemPlusJSONResponse) VisitUpdateProductResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(412)

	return json.NewEncoder(w).Encode(response)
}

type UpdateProduct500ApplicationProblemPlusJSONResponse Problem

func (response UpdateProduct500ApplicationProblemPlusJSONResponse) VisitUpdateProductResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Create a new product
	// (POST /v1/product/create)
	CreateProduct(ctx context.Context, request CreateProductRequestObject) (CreateProductResponseObject, error)
	// Get a product by ID
	// (GET /v1/product/get/{id})
	GetProductById(ctx context.Context, request GetProductByIdRequestObject) (GetProductByIdResponseObject, error)
	// Get a paginated list of products with filtering and sorting
	// (GET /v1/product/list)
	GetList(ctx context.Context, request GetListRequestObject) (GetListResponseObject, error)
	// Update an existing product
	// (PUT /v1/product/update)
	UpdateProduct(ctx context.Context, request UpdateProductRequestObject) (UpdateProductResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// CreateProduct operation middleware
func (sh *strictHandler) CreateProduct(ctx *gin.Context) {
	var request CreateProductRequestObject

	var body CreateProductJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateProduct(ctx, request.(CreateProductRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateProduct")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(CreateProductResponseObject); ok {
		if err := validResponse.VisitCreateProductResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetProductById operation middleware
func (sh *strictHandler) GetProductById(ctx *gin.Context, id string) {
	var request GetProductByIdRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetProductById(ctx, request.(GetProductByIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProductById")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetProductByIdResponseObject); ok {
		if err := validResponse.VisitGetProductByIdResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetList operation middleware
func (sh *strictHandler) GetList(ctx *gin.Context, params GetListParams) {
	var request GetListRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetList(ctx, request.(GetListRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetList")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetListResponseObject); ok {
		if err := validResponse.VisitGetListResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateProduct operation middleware
func (sh *strictHandler) UpdateProduct(ctx *gin.Context) {
	var request UpdateProductRequestObject

	var body UpdateProductJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateProduct(ctx, request.(UpdateProductRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateProduct")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(UpdateProductResponseObject); ok {
		if err := validResponse.VisitUpdateProductResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xYb2/bthP+KgR/fdEfZsWS4j+J36Xt2gUohqDthmFBBtDSyWYhkgp5SuMF/u4DqT+W",
	"bNpNirVLgAR5YVHk8eHxuefudEcTJQolQaKhsztqkiUI5n5eaDXPQdifKZhE8wK5knRGP7x9PT0Jp6Se",
	"QN4AMp4bOqCFVgVo5GCqVXbc/sJVAXRGDWouF3Q9oKC10m4SRxDuR39txiFPvUsFGMMW4Hm3HjQjav4Z",
	"EqSbAaY1W9lnLg0ymbjlmdKCIZ3RUnM62N3JIMPSdDbiEmEB2tnlmIMXH2qWwLkfezXwtZ3XA6rhuuQa",
	"Ujq7rN42O7aorjyHvdAqLRN8zw1+AFMoaWDXs63D2x8vNGR0Rv833FBhWPNgWJtszXlcWtS30SfJ61Jr",
	"kEjsWyJLMQdNBxRumSis46KBx6mG/+2x9KtbTFRGHGJSgHZWu+bi0GcPFbJ81+AnO1xjas32wIUec1u3",
	"0iyqkTjozY4H7mb/vSQMYaH0qqJOi4VG8TGMxpNpACen8yCK0+OAjcaTYBRPJtEomo7CMKSDDqVKnvrY",
	"nGhgCOkZ9s3HYXwchFEQRp/CcOb+/+yaSxlCgFyAz2bPr12rv/DFMrguWc5xRYxgGoulkkC+cFwSlt7Y",
	"EExJBgxLDcZnGiSb59D3BeoS2qlzpXJg0gX1lssm05P5dMSOJ1kSz+NJOE4m2Xh66nULF2yxL1yFSnnG",
	"D/gs/gafSSagb+7jxj9CpZCTP3zrCs2T/sIoPBq3E+sQWw/odckkclxtzfUFyA1os3130depbx3ZLK0P",
	"1ODrbL+5wy75el7dDZS10+hM7Ubt2cU5yZQmgkm24HJBiiqiTKuNsybIyNnFeQfijEZH4dFpbE+sCpCs",
	"4HRGj4/Co9AFMC5dAA5vomFtc1jhdUGqjLt9G6rMQrFcoa/d+3o7WrkHDL5SqXN7oiSCdOtYUeQ8cSuH",
	"n03l60pcv7sEFAwRtD3/X5dhcMqC7Cx4e3V3sg66j6N1cBkF46vu2PE6uDw5ZfOzVzvDnccoXr/4vqog",
	"2O17kAtcWoXviPK/IxNPzK0dpbqX1HWc5xKa4LJ9/nZdOmA1foBqCXbLRSmckerPmarGwoeo2j0t7ROz",
	"Wr02UrWjY36R2tiwdHMDVWZ3kRyH4YN04EEl2Ho7xlrdq2WWmDJJwJiszHNXoo0OwimqOv6nB8Ny7YEH",
	"zu8s56mzTVyhbyGMfyyEc2ljlOXkI+gb0OTnCoctMkshmF61Ik4YkfClySZuSjcTLACHdzxdWywL8KSC",
	"d4C1+19Z4bb6oJkABNvfXN5RbuHYJNOkylmVQPsEGnSOvN0OXD0OcmlAzeHGS6/Rj7zbBpBUSDJVyvSR",
	"8usdIGENsch8Rc7f7NAr51V5sY9atpfb5dSWPzYtFnkpSoNkDmThyK0JLpkk4f/poCLidQl6tWFi3b3s",
	"52K3LGxV1Vsi3rdtIy8FuyVRuBdT3UrdA1O8Jf8PhfiW59ZF8xWp5Z/UzbUf2CZHeLD4iw7fnpCnBBUx",
	"SltS7HOC0tjfSNpjXR6otvfX2JuU3p2z89VhG+pHi1Dp1NKKmQRkastupYmdVj3tu0O3qoc/hYyVueuO",
	"wCQu41YHYu7JDfag1tP+AzHsfT/xxL59b3ndNCAHlfE58e4VRtvGuXIl33aoawgyF52WckymLlyar2Nd",
	"AS2LtOnUSo+E/uZePzdqz43ac6P2xBq1vZ+nDif53U9VX2/xNls9oWavUr5HmXNGUfxDIVSXZ4jgRjBM",
	"lo8071XJiDBJ4JYb7HzEtBbX/wQAAP//ukVH44wbAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
