name: Generate and Commit Go SDK

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  generate-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Generate Go SDK using Makefile
        run: make all

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit generated SDK to `generated` branch
        run: |
          git checkout -B generated
          git add gen/
          git commit -m "chore: generate SDK for release ${{ github.ref_name }}" || echo "No changes to commit"
          git push origin generated --force

      - name: Create GitHub Release with generated files
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: |
            gen/client.gen.go
            gen/server.gen.go
            gen/models.gen.go
