name: Generate and Release Go SDK

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Put the next version (e.g. v1.0.0)"
        required: true

permissions:
  contents: write

jobs:
  generate-sdk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # To allow tag creation

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.2"

      - name: Generate Go SDK
        run: make all

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit to `generated` branch
        run: |
          git checkout -B generated
          git add gen/
          git commit -m "chore: generate SDK for release ${{ github.event.inputs.version }}" || echo "No changes to commit"
          git push origin generated --force

      - name: Create tag on generated branch
        run: |
          git tag ${{ github.event.inputs.version }}
          git push origin ${{ github.event.inputs.version }}

      - name: Create GitHub Release with generated code
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          files: |
            gen/client.gen.go
            gen/server.gen.go
            gen/models.gen.go
